### ISSUE TITLE
请问这个后续有兼容creator 2.4 计划吗？

### ISSUE THREAD

**Issue by gamegg** [zhengfasheng/QuickFramework#1]
请问这个后续有兼容creator 2.4 计划吗？

**Comment by zhengfasheng** [comment]
可以考虑的，这个问题



---原始邮件---
发件人: "gamegg"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 下午5:48
收件人: "zhengfasheng/QuickFramework"<QuickFramework@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhengfasheng/QuickFramework] 请问这个后续有兼容creator 2.4 计划吗？ (#1)




 
请问这个后续有兼容creator 2.4 计划吗？

**Comment by zhengfasheng** [comment]
目前对2.4.0版本已经有兼容，2.4.0版本请拉取分支2.4.0

**Comment by gamegg** [comment]
> 目前对2.4.0版本已经有兼容，2.4.0版本请拉取分支2.4.0

感谢感谢！~

**Comment by zhengfasheng** [comment]
android平台的还没测试，目前只跑了win32平台的，已经ok了，资源的释放，内存问题还没系统测试，后面会有持续更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gamegg"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 中午11:38
收件人: "zhengfasheng/QuickFramework"<QuickFramework@noreply.github.com&gt;; 
抄送: "547933762"<547933762@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zhengfasheng/QuickFramework] 请问这个后续有兼容creator 2.4 计划吗？ (#1)





  
目前对2.4.0版本已经有兼容，2.4.0版本请拉取分支2.4.0
  
感谢感谢！~

**Comment by gamegg** [comment]
> android平台的还没测试，目前只跑了win32平台的，已经ok了，资源的释放，内存问题还没系统测试，后面会有持续更新
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gamegg"<notifications@github.com&gt;; 发送时间: 2020年7月15日(星期三) 中午11:38 收件人: "zhengfasheng/QuickFramework"<QuickFramework@noreply.github.com&gt;; 抄送: "547933762"<547933762@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [zhengfasheng/QuickFramework] 请问这个后续有兼容creator 2.4 计划吗？ (#1) 目前对2.4.0版本已经有兼容，2.4.0版本请拉取分支2.4.0 感谢感谢！~ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，我有个疑问，刚测试了下，web下预览是正常的，但是 微信小游戏 是不能正常加载子游戏的，因为我们是做教育产品的，所以寻找这类能够加载子游戏的框架，您的项目非常好，感谢！

**Comment by zhengfasheng** [comment]
你再Github上提问题吧，我怕这里有时关注不到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gamegg"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 中午11:50
收件人: "TopDiscover/QuickFramework"<QuickFramework@noreply.github.com&gt;; 
抄送: "547933762"<547933762@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [TopDiscover/QuickFramework] 请问这个后续有兼容creator 2.4 计划吗？ (#1)





  
android平台的还没测试，目前只跑了win32平台的，已经ok了，资源的释放，内存问题还没系统测试，后面会有持续更新
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gamegg"<notifications@github.com&gt;; 发送时间: 2020年7月15日(星期三) 中午11:38 收件人: "zhengfasheng/QuickFramework"<QuickFramework@noreply.github.com&gt;; 抄送: "547933762"<547933762@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [zhengfasheng/QuickFramework] 请问这个后续有兼容creator 2.4 计划吗？ (#1) 目前对2.4.0版本已经有兼容，2.4.0版本请拉取分支2.4.0 感谢感谢！~ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
大佬，我有个疑问，刚测试了下，web下预览是正常的，但是 微信小游戏 是不能正常加载子游戏的，因为我们是做教育产品的，所以寻找这类能够加载子游戏的框架，您的项目非常好，感谢！
